resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

modules:
  parabricks: "main"
  prealignment: "master"
  qc: "master"

default_container: ""

reference:
  fasta: ""
  sites: ""
  wgs_intervals: ""

cnvkit_batch:
  method: "wgs"

multiqc:
  container: ""
  qc_files:
    - ""
