default_resources:
  threads: 1
  time: "4:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: "core"

sentieon:
  threads: 20
  time: "24:00:00"

tnscope:
  threads: 40

pindel_call:
  threads: 4

pindel2vcf:
  threads: 4

manta_run_workflow_tn:
  threads: 4
  time: "8:00:00"
  mem_mb: 24576
  mem_per_cpu: 6144
