default_resources:
  gres: ""
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""

pbrun_fq2bam:
  gres: ""
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""

pbrun_mutectcaller_t:
  gres: ""
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""

pbrun_mutectcaller_tn:
  gres: ""
  mem_mb: 0
  mem_per_cpu: 0
  partition: ""
  threads: 0
  time: ""
