$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  resources:
    type: string
    description: path to resources.yaml file

  samples:
    type: string
    description: path to samples.tsv file

  units:
    type: string
    description: path to units.tsv file

  output:
    type: string
    description: path to output_files.json file

  modules:
    type: object
    description: map module to version/branch/tag
    properties:
      alignment:
        type: string
        description: version/branch/tag
      annotation:
        type: string
        description: version/branch/tag
      cnv_sv:
        type: string
        description: version/branch/tag
      compression:
        type: string
        description: version/branch/tag
      filtering:
        type: string
        description: version/branch/tag
      fusions:
        type: string
        description: version/branch/tag
      parabricks:
        type: string
        description: version/branch/tag
      prealignment:
        type: string
        description: version/branch/tag
      qc:
        type: string
        description: version/branch/tag
      misc:
        type: string
        description: version/branch/tag
    required:
      - alignment
      - annotation
      - cnv_sv
      - compression
      - prealignment
      - filtering
      - fusions
      - qc
      - misc

  default_container:
    type: string
    description: name or path to a default docker/singularity container

  reference:
    type: object
    properties:
      design_bed:
        type: string
        description: path to reference design bed file
      design_intervals:
        type: string
        description: path to design intervals file for hsmetrics
      fai:
        type: string
        description: path to reference fasta index file
      fasta:
        type: string
        description: path to reference fasta file
      fasta_rna:
        type: string
        description: path to reference fasta file for rna used by picard_collect_alignment_summary_metrics
      genome_dir:
        type: string
        description: path to genome directory for star align
      sites:
        type: string
        description: path to known sites list file
      wgs_intervals:
        type: string
        description: path to wgs interval file
    required:
      - design_bed
      - design_intervals
      - fai
      - fasta
      - fasta_rna
      - genome_dir
      - sites
      - wgs_intervals

  trimmer_software:
    type: string
    description: name of rule to be used for trimming

  arriba:
    type: object
    properties:
      assembly:
        type: string
        description: path to assembly fasta file
      blacklist:
        type: string
        description: path to blacklist tsv.gz file
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to be forwarded
      gtf:
        type: string
        description: path to gtf file
    required:
      - assembly
      - blacklist
      - container
      - gtf

  arriba_draw_fusion:
    type: object
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      cytobands:
        type: string
        description: path to cytobands tsv file
      gtf:
        type: string
        description: path to gtf file
      protein_domains:
        type: string
        description: path to protein domains gff file
    required:
      - container
      - cytobands
      - gtf
      - protein_domains

  cnvkit_batch:
    type: object
    description: parameters for cnvkit_batch
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      method:
        type: string
        description: cnvkit method to be used, should be wgs
      normal_reference:
        type: string
        description: path to panel of normals file
    required:
      - container
      - method
      - normal_reference

  cnvkit_call:
    type: object
    description: parameters for cnvkit_call
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  cnvkit_diagram:
    type: object
    description: parameters for cnvkit_diagram
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  cnvkit_scatter:
    type: object
    description: parameters for cnvkit_scatter
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to be forwarded
      cna:
        type: object
        description: cna genes to be highlighted in cnvkit scatterplots
    required:
      - container

  cnvkit_scatter_whole:
    type: object
    description: parameters for cnvkit_scatter_whole
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to be forwarded
    required:
      - container

  cnvkit_table:
    type: object
    description: parameters for cnvkit_scatter_whole
    properties:
      bedfile:
        type: string
        description: path to bed file
      container:
        type: string
        description: name or path to docker/singularity python container
      cyto_coordinates:
        type: string
        description: path to a cyto coordinate txt file
    required:
      - bedfile
      - container
      - cyto_coordinates

  cnvkit_vcf:
    type: object
    description: parameters for cnvkit_vcf
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  manta_config_t:
    type: object
    description: parameters for config_manta_t
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  manta_config_tn:
    type: object
    description: parameters for config_manta_tn
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  crumble:
    type: object
    description: parameters for crumble
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to be forwarded
    required:
      - container

  fastp_pe:
    type: object
    description: parameters for fastp_pe
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  fastqc:
    type: object
    description: parameters for fastqc
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  filter_vcf:
    type: object
    description: parameter for filtering vcfs
    properties:
      container:
        type: string
        description: name or path of container
      germline:
        type: string
        description: path to config file for filtering out germline snvs for baf plots
      required:
        - germline

  fusioncatcher:
    type: object
    properties:
      container:
        type: string
        description: name or path of container
      genome_path:
        type: string
        description: path to fusionscatcher genome resource dir
    required:
      - container
      - genome_path

  manta_run_workflow_t:
    type: object
    description: parameters for manta_run_workflow_t
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  manta_run_workflow_tn:
    type: object
    description: parameters for manta_run_workflow_tn
    properties:
      bed_files:
        type: object
        description: map of bed files
        properties:
          all:
            type: string
            description: path to bed file containing relevant genes for ALL
          aml:
            type: string
            description: path to bed file containing relevant genes for AML
        required:
          - all
          - aml
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  mosdepth:
    type: object
    description: parameters for mosdepth
    properties:
      by:
        type: string
        description: window size
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters to be forwarded
    required:
      - by
      - container

  mosdepth_bed:
    type: object
    description: parameters for mosdepth_bed
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      design_bed:
        type: string
        description: path to design bed file
    required:
      - container
      - design_bed

  multiqc:
    type: object
    description: parameters for multiqc
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      reports:
        type: object
        description: report names
        properties:
          DNA:
            type: object
            description: information to compile report correctly
            properties:
              config:
                type: string
                description: MultiQC report config
              included_unit_types:
                type: array
                description: unit types to be part of this report
              qc_files:
                type: array
                description: file names which should be included in report
            required:
              - config
              - included_unit_types
              - qc_files
          RNA:
            type: object
            description: information to compile report correctly
            properties:
              config:
                type: string
                description: MultiQC report config
              included_unit_types:
                type: array
                description: unit type to be part of this report
              qc_files:
                type: array
                description: file names which should be included in report
            required:
              - config
              - included_unit_types
              - qc_files
        required:
          - DNA
          - RNA
    required:
      - container
      - reports

  peddy:
    type: object
    description: parameters for peddy
    properties:
      containter:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: additional parameters for peddy
    required:
      - container
      - extra

  picard_collect_alignment_summary_metrics:
    type: object
    description: parameters for picard_collect_alignment_summary_metrics
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  picard_collect_duplication_metrics:
    type: object
    description: parameters for picard_collect_duplication_metrics
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  picard_collect_gc_bias_metrics:
    type: object
    description: parameters for picard_collect_gc_bias_metrics
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  picard_collect_hs_metrics:
    type: object
    description: parameters for picard_collect_gc_bias_metrics
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  picard_collect_multiple_metrics:
    type: object
    description: parameters for picard_collect_multiple_metrics
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      output_ext:
        type: array
        description: list of metric file suffixes that should be produced
    required:
      - container

  picard_collect_wgs_metrics:
    type: object
    description: parameters for picard_collect_wgs_metrics
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  pindel_update_vcf_sequence_dictionary:
    type: object
    description: parameters for pindel_update_vcf_sequence_dictionary
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  pindel_call:
    type: object
    description: parameters for pindel_call
    properties:
      include_bed:
        type: string
        description: path to bed file containing region of interest
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - include_bed
      - container

  pindel2vcf:
    type: object
    description: parameters for pindel2vcf
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  rseqc_gene_body_coverage:
    type: object
    properties:
      bed:
        type: string
        description: path to bed file
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - bed
      - container

  rseqc_inner_distance:
    type: object
    properties:
      bed:
        type: string
        description: path to bed file
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - bed
      - container

  sample_order_multiqc:
    type: object
    properties:
      sample_sheet:
        type: string
        description: Path to SampleSheet.csv
    required:
      - sample_sheet

  simple_sv_annotation:
    type: object
    description: parameters for simple_sv_annotation
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      fusion_pairs:
        type: string
        description: path to list of fusion pairs
      panel:
        type: string
        description: path to list of genes
    required:
      - container
      - fusion_pairs
      - panel

  snpeff:
    type: object
    description: parameters for snpeff
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      db:
        type: string
        description: path to snpeff db
    required:
      - container
      - db

  sortmerna:
    type: object
    description: parameters for sortmerna
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      fasta:
        type: array
        description: list of paths to fasta files containing ribosomal rna sequences
      index:
        type: string
        description: path to sortmerna index for fasta files
    required:
      - container
      - fasta
      - index

  spring:
    type: object
    description: parameters for spring
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
    required:
      - container

  star:
    type: object
    description: parameters for star
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      genome_index:
        type: string
        description: path to genome resource
      extra:
        type: string
        description: extra parameters to be forwarded
    required:
      - container
      - genome_index

  star_fusion:
    type: object
    description: parameters for star_fusion
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      genome_path:
        type: string
        description: path to genome resource
      extra:
        type: string
        description: extra parameters to be forwarded
    required:
      - container
      - genome_path

  vep:
    type: object
    description: parameters for vep
    properties:
      container:
        type: string
        description: name or path to docker/singularity container
      vep_cache:
        type: string
        description: path to vep cache
    required:
      - container
      - vep_cache

required:
  - resources
  - samples
  - units
  - output
  - modules
  - default_container
  - reference
  - trimmer_software
  - arriba
  - arriba_draw_fusion
  - cnvkit_batch
  - cnvkit_call
  - cnvkit_diagram
  - cnvkit_scatter
  - cnvkit_scatter_whole
  - cnvkit_table
  - cnvkit_vcf
  - manta_config_t
  - manta_config_tn
  - crumble
  - fastp_pe
  - fastqc
  - filter_vcf
  - manta_run_workflow_t
  - manta_run_workflow_tn
  - mosdepth
  - mosdepth_bed
  - multiqc
  - picard_collect_alignment_summary_metrics
  - picard_collect_duplication_metrics
  - picard_collect_gc_bias_metrics
  - picard_collect_hs_metrics
  - picard_collect_multiple_metrics
  - picard_collect_wgs_metrics
  - pindel_update_vcf_sequence_dictionary
  - pindel_call
  - pindel2vcf
  - rseqc_gene_body_coverage
  - rseqc_inner_distance
  - sample_order_multiqc
  - simple_sv_annotation
  - snpeff
  - spring
  - star
  - star_fusion
  - vep
