output: "../../config/output_files.json"

reference:
  design_bed: "reference/homo_sapiens.wgs.bed"
  fasta: "reference/reference.fasta"
  fai: "reference/reference.fasta.fai"
  fasta_rna: "reference/reference.fasta"
  genome_dir: "reference"
  sites: "reference/sites.vcf.gz"
  wgs_intervals: "reference/wgs.interval_list"
  design_intervals: "reference/wgs.interval_list" #HSMetrics

arriba:
  assembly: "reference/assembly.fasta"
  blacklist: "reference/arriba_blacklist.txt"
  extra: "-p abc.gff3 -k abc.tsv.gz"
  gtf: "reference/assembly.gtf"

arriba_draw_fusion:
  cytobands: "reference/cytobands.tsv"
  gtf: "reference/assembly.gtf"
  protein_domains: "reference/proteindomain.gff3"

bcftools_SNV:
  all: "reference/all.bed"
  aml: "reference/aml.bed"

bcftools_SV:
  all: "reference/all.bed"
  aml: "reference/aml.bed"

cnvkit_batch:
  normal_reference: "reference/cnvkit.cnn"

cnvkit_table:
  bedfile: "reference/cna_genes.bed"
  container: "/path/python3.9-0.1.0.sif"
  cyto_coordinates: "reference/cyto_coordinates.txt"
  # log_thresholds: "-0.19,0.2"
  # ploidy: "3"

filter_vcf:
  germline: "../../config/config_germline_filter.yaml"

fusioncatcher:
  genome_path: "reference/"

mosdepth_bed:
  design_bed: "reference/exome.bed"

multiqc:
  reports:
    DNA:
      config: "../../config/multiqc_dna_config.yaml"
    RNA:
      config: "../../config/multiqc_rna_config.yaml"

pindel_call:
  bedfile: "reference/pindel.bed"


rseqc_gene_body_coverage:
  bed: "reference/gene_model.bed"

rseqc_inner_distance:
  bed: "reference/gene_model.bed"

simple_sv_annotation:
  panel: "reference/panel.txt"
  fusion_pairs: "reference/fusion_pairs.txt"

snpeff:
  db: "SnpEff/GRCh38.99"

sortmerna:
  fasta:
    - "reference/id.fasta"
  index: "reference/"

star:
  genome_index: "reference/"

star_fusion:
  genome_path: "reference/"

vep:
  vep_cache: "reference/vep"
