output: "../../config/output_files.json"

modules:
  alignment: "906d25d0d4791eb5a54cba9954fddf29e27b85dd"
  annotation: "e58432c3467db31621ab51a16034a026cf2a2c84"
  cnv_sv: "v0.4.1"
  compression: "v1.1.0"
  filtering: "b7f4dc3"
  fusions: "12f8354"
  parabricks: "v0.2.0"
  prealignment: "v0.5.0"
  qc: "v0.3.0"
  misc: "v0.1.0"

default_container: "docker://hydragenetics/common:0.1.9"

reference:
  design_bed: "reference/homo_sapiens.wgs.bed"
  fasta: "reference/reference.fasta"
  fai: "reference/reference.fasta.fai"
  fasta_rna: "reference/reference.fasta"
  genome_dir: "reference"
  sites: "reference/sites.vcf.gz"
  wgs_intervals: "reference/wgs.interval_list"
  design_intervals: "reference/wgs.interval_list" #HSMetrics
  design_intervals_gatk_cnv: "reference/wgs.interval_list"

arriba:
  assembly: "reference/assembly.fasta"
  blacklist: "reference/arriba_blacklist.txt"
  extra: "-p abc.gff3 -k abc.tsv.gz"
  gtf: "reference/assembly.gtf"

arriba_draw_fusion:
  cytobands: "reference/cytobands.tsv"
  gtf: "reference/assembly.gtf"
  protein_domains: "reference/proteindomain.gff3"

bcftools_SNV:
  all: "reference/all.bed"
  aml: "reference/aml.bed"

bcftools_SV:
  all: "reference/all.bed"
  aml: "reference/aml.bed"

cnvkit_batch:
  normal_reference: "reference/cnvkit.cnn"

cnvkit_table:
  bedfile: "reference/cna_genes.bed"
  container: "/path/python3.9-0.1.0.sif"
  cyto_coordinates: "reference/cyto_coordinates.txt"
  # log_thresholds: "-0.19,0.2"
  # ploidy: "3"

cnvkit_vcf:
  container: "docker://python:3.9.9-slim-buster"

crumble:
  container: "docker://hydragenetics/crumble:0.8.3"
  extra: "-O CRAM"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

filter_vcf:
  germline: "../../config/config_germline_filter.yaml"

fusioncatcher:
  genome_path: "reference/"

manta_config_tn:
  container: "docker://hydragenetics/manta:v1.6.0"

manta_config_t:
  container: "docker://hydragenetics/manta:v1.6.0"

manta_run_workflow_t:
  container: "docker://hydragenetics/manta:v1.6.0"

manta_run_workflow_tn:
  container: "docker://hydragenetics/manta:v1.6.0"

mosdepth:
  by: "500"
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: "--fast-mode --no-per-base"

mosdepth_bed:
  design_bed: "reference/exome.bed"

multiqc:
  reports:
    DNA:
      config: "../../config/multiqc_dna_config.yaml"
    RNA:
      config: "../../config/multiqc_rna_config.yaml"

peddy:
  container: "docker://hydragenetics/peddy:0.4.8"
  extra: "--sites hg38 "

pindel_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

pindel_call:
  include_bed: "reference/pindel.bed"

rseqc_gene_body_coverage:
  bed: "reference/gene_model.bed"

rseqc_inner_distance:
  bed: "reference/gene_model.bed"

simple_sv_annotation:
  panel: "reference/panel.txt"
  fusion_pairs: "reference/fusion_pairs.txt"

snpeff:
  db: "SnpEff/GRCh38.99"

sortmerna:
  fasta:
    - "reference/id.fasta"
  index: "reference/"

star:
  genome_index: "reference/"

star_fusion:
  genome_path: "reference/"

vep:
  vep_cache: "reference/vep"
