resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

modules:
  cnv_sv: "patch-cnvkit-call"
  parabricks: "develop"
  prealignment: "develop"
  qc: "develop"

default_container: "docker://marrip/common:1.1.1"

reference:
  fasta: "reference/reference.fasta"
  sites: "reference/sites.vcf.gz"
  wgs_intervals: "reference/wgs.interval_list"

trimmer_software: "fastp"

cnvkit_call:
  container: "docker://marrip/cnvkit:0.9.9"
  extra: "-m wgs"

config_manta_tn:
  container: "docker://marrip/manta:v1.6.0"

multiqc:
  container: "docker://marrip/multiqc:1.11"
  qc_files:
    - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
    - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
    - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"
    - "qc/mosdepth/{sample}_{type}.regions.bed.gz"
    - "qc/mosdepth/{sample}_{type}.regions.bed.gz.csi"
    - "qc/picard_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
    - "qc/picard_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
    - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.pdf"
    - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.detail_metrics"
    - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.alignment_summary_metrics"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.base_distribution_by_cycle_metrics"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.base_distribution_by_cycle.pdf"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.insert_size_metrics"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.insert_size_histogram.pdf"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_by_cycle_metrics"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_by_cycle.pdf"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_distribution_metrics"
    - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_distribution.pdf"
    - "qc/picard_collect_wgs_metrics/{sample}_{type}.txt"
    - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"

manta_run_workflow_tn:
  container: "docker://marrip/manta:v1.6.0"

mosdepth:
  container: "docker://marrip/mosdepth:0.3.2"

picard_alignment_summary_metrics:
  container: "docker://broadinstitute/gatk:4.2.0.0"

picard_duplication_metrics:
  container: "docker://broadinstitute/gatk:4.2.0.0"

picard_collect_gc_bias_metrics:
  container: "docker://broadinstitute/gatk:4.2.0.0"

picard_collect_multiple_metrics:
  container: "docker://broadinstitute/gatk:4.2.0.0"
  output_ext:
    - "alignment_summary_metrics"
    - "base_distribution_by_cycle_metrics"
    - "base_distribution_by_cycle.pdf"
    - "insert_size_metrics"
    - "insert_size_histogram.pdf"
    - "quality_by_cycle_metrics"
    - "quality_by_cycle.pdf"
    - "quality_distribution_metrics"
    - "quality_distribution.pdf"

picard_collect_wgs_metrics:
  container: "docker://broadinstitute/gatk:4.2.0.0"
