resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"
output: "../../config/output_files.json"

modules:
  alignment: "906d25d0d4791eb5a54cba9954fddf29e27b85dd"
  annotation: "e58432c3467db31621ab51a16034a026cf2a2c84"
  cnv_sv: "4b3f69ef0f0781b7943ca27ca16b940470c27118"
  compression: "v1.1.0"
  filtering: "b7f4dc3"
  fusions: "1d538b680b6896d733bf57fb1e889c974c1f6c61"
  parabricks: "v0.2.0"
  prealignment: "v0.2.0"
  qc: "178be68"
  misc: "v0.1.0"

default_container: "docker://hydragenetics/common:0.1.9"

reference:
  fai: "reference/reference.fasta.fai"
  fasta: "reference/reference.fasta"
  genome_dir: "reference"
  sites: "reference/sites.vcf.gz"
  wgs_intervals: "reference/wgs.interval_list"
  design_intervals: "reference/wgs.interval_list" #HSMetrics

trimmer_software: "fastp_pe"

arriba:
  assembly: "reference/assembly.fasta"
  blacklist: "reference/arriba_blacklist.txt"
  container: "docker://hydragenetics/arriba:2.2.1"
  gtf: "reference/assembly.gtf"

bedtools_intersect:
  extra: "-header"

cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  method: "wgs"
  normal_reference: "reference/cnvkit.cnn"

cnvkit_diagram:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_call:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_scatter:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  extra: "-c {locus} --y-min -5 --y-max 5"

cnvkit_scatter_whole:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  extra: "--y-min -5 --y-max 5"

cnvkit_table:
  bedfile: "reference/cna_genes.bed"
  cyto_coordinates: "reference/cyto_coordinates.txt"
  # log_thresholds: "-0.19,0.2"
  # ploidy: "3"

cnvkit_vcf:
  container: "docker://python:3.9.9-slim-buster"

config_manta_tn:
  container: "docker://hydragenetics/manta:v1.6.0"

crumble:
  container: "docker://hydragenetics/crumble:0.8.3"
  extra: "-O CRAM"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

filter_vcf:
  germline: "../../config/config_germline_filter.yaml"

fusioncatcher:
  container: "docker://hydragenetics/fusioncatcher:1.33"
  genome_path: "reference/fusioncatcher"

imagemagick_convert:
  container: "docker://hydragenetics/imagemagick:7.1.0_20"

manta_run_workflow_t:
  bed_files:
    all: "reference/all.bed"
    aml: "reference/aml.bed"
  container: "docker://hydragenetics/manta:v1.6.0"

manta_run_workflow_tn:
  bed_files:
    all: "reference/all.bed"
    aml: "reference/aml.bed"
  container: "docker://hydragenetics/manta:v1.6.0"

mosdepth:
  by: "500"
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: "--fast-mode --no-per-base"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  design_bed: "reference/exome.bed"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    DNA:
      config: "../../config/multiqc_dna_config.yaml"
      included_unit_types: ['T', 'N']
      qc_files:
        - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{barcode}_{type}.json"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.summary.txt"
        - "qc/mosdepth/{sample}_{type}.regions.bed.gz"
        - "qc/mosdepth/{sample}_{type}.regions.bed.gz.csi"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.pdf"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.detail_metrics"
        - "qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt" #behover bed
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.alignment_summary_metrics"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.base_distribution_by_cycle_metrics"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.base_distribution_by_cycle.pdf"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.insert_size_metrics"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.insert_size_histogram.pdf"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_by_cycle_metrics"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_by_cycle.pdf"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_distribution_metrics"
        - "qc/picard_collect_multiple_metrics/{sample}_{type}.quality_distribution.pdf"
        - "qc/picard_collect_wgs_metrics/{sample}_{type}.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
    RNA:
      included_unit_types:
        - "R"
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_{read}_fastqc.zip"
        - "qc/mosdepth_bed/{sample}_{type}.mosdepth.summary.txt"
        - "qc/rseqc_gene_body_coverage/{sample}_{type}.geneBodyCoverage.txt"
        - "qc/rseqc_inner_distance/{sample}_{type}.inner_distance.txt"
        - "prealignment/fastp_pe/{sample}_{flowcell}_{lane}_{barcode}_{type}.json"
        - "prealignment/sortmerna/{sample}_{type}.rrna.log"

pbrun_mutectcaller_t:
  bed_files:
    all: "reference/all.bed"
    aml: "reference/aml.bed"

pbrun_mutectcaller_tn:
  bed_files:
    all: "reference/all.bed"
    aml: "reference/aml.bed"

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_gc_bias_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_multiple_metrics:
  container: "docker://hydragenetics/picard:2.25.0"
  output_ext:
    - "alignment_summary_metrics"
    - "base_distribution_by_cycle_metrics"
    - "base_distribution_by_cycle.pdf"
    - "insert_size_metrics"
    - "insert_size_histogram.pdf"
    - "quality_by_cycle_metrics"
    - "quality_by_cycle.pdf"
    - "quality_distribution_metrics"
    - "quality_distribution.pdf"

picard_collect_wgs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_update_vcf_sequence_dictionary:
  container: "docker://hydragenetics/picard:2.25.0"

pindel_call:
  bedfile: "reference/pindel.bed"
  container: "docker://hydragenetics/pindel:0.2.5b9"

pindel2vcf:
  container: "docker://hydragenetics/pindel:0.2.5b9"

rseqc_gene_body_coverage:
  bed: "reference/gene_model.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

rseqc_inner_distance:
  bed: "reference/gene_model.bed"
  container: "docker://hydragenetics/rseqc:4.0.0"

sample_order_multiqc:
  sample_sheet: "SampleSheet.csv"

simple_sv_annotation:
  container: "docker://hydragenetics/simple_sv_annotation:2019.02.18"
  panel: "reference/panel.txt"
  fusion_pairs: "reference/fusion_pairs.txt"

snpeff:
  container: "docker://hydragenetics/snpeff:5.0"
  db: "SnpEff/GRCh38.99"

spring:
  container: "docker://hydragenetics/spring:1.0.1"

star:
  container: "docker://hydragenetics/star:2.7.10a"
  genome_index: "reference/star_index"

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: "reference/star_fusion"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache: "reference/vep"
  extra: "--assembly GRCh38 --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class"
